### ISSUE TITLE
a way to split component definition and template into different files

### ISSUE THREAD

**Issue by patricklx** [ember-template-imports/ember-template-imports#44] opened 2022-08-17 13:10 UTC
i found that i can do 

```
import { hbs } from 'ember-template-imports';
import { getComponentTemplate } from '@ember/component';

const template = hbs`<div></div>`;
export default getComponentTemplate(template);
```

but setting the export to the static template in the component does not work. but the ember resolver finds it and can use it.

but there could be a default behaviour if there is an exising backing component. just like for colocation.
this would work well in combination with gts/gjs extension and use existing colocation code to also handle those extensions.

like this the migration to template imports would be even easier

**Comment by chriskrycho** [comment] 2022-08-17 16:10
If that happens to work, it’s basically an accident, not intended behavior. We explicitly chose *not* to support a mixed mode as part of [RFC 0779](https://rfcs.emberjs.com/id/0779-first-class-component-templates). While we understand that many folks in the community feel having separate files is very convenient, it is not the intended path forward and we don't plan to introduce support for it accordingly.

If it's something you feel strongly about, we *have* talked about ways it could in principle be supported, but that would require considerable further design work, which I personally would not block but also do not agree with, so you’d need to find someone else on the Framework team who strongly values it to work with you to do design to support it.

Closing this as it's not something we'll be implementing here without an RFC to design that. Thanks!

**Closed by chriskrycho** 2022-08-17 16:10 UTC
Labels: invalid
