### ISSUE TITLE
Handlebars comments within `<template>` cause parse error if they include backtick characters

### ISSUE THREAD

**Issue by chriskrycho** [ember-template-imports/ember-template-imports#93] opened 2022-12-02 04:43 UTC
The following code breaks our parsing, likely because of the way we use template string literals as an intermediate format, and suggesting we need to introduce an escaping step in between:

```js
<template>`</template>
```

The presence of *any* backtick character causes this failure, as the above example shows. The way I've run into this is by migrating component templates which included a writeup with Markdown syntax with the inline code block syntax; but there are plenty of other scenarios where it might come up.

**Comment by NullVoxPopuli** [comment] 2023-10-19 13:40
Should be resolved in v4. Thanks for reporting!
If this is still an issue, lemme know and we can reopen.

**Closed by NullVoxPopuli** 2023-10-19 13:40 UTC
Labels: bug

**Comment by bertdeblock** [comment] 2025-04-05 12:45
@NullVoxPopuli It seems like this is still an issue. [Discord link](https://discord.com/channels/480462759797063690/518154533143183377/1358055645399617729).

**Comment by NullVoxPopuli** [comment] 2025-04-05 12:56
Confirmed in discord the issue is with glint (rather than ember-template-imports). likely due to the backtick support it has for typing 'hbs' things. We should get rid of that.
