### ISSUE TITLE
yielded components on a hash are linted as not defined when yielded on named blocks

### ISSUE THREAD

**Issue by cah-brian-gantzler** [ember-template-imports/ember-template-imports#186] opened 2023-08-10 16:08 UTC
Not sure which addon is doing the linting, this one or https://github.com/ember-template-lint/ember-template-lint. Starting here

When a component is yielded on a named block, then used, the linter states that the component is undefined. This is in a test. Have not yet converted the actual use to a gjs. 
```js
await render(<template>
      <Stargate
        @onCancel={{(noop)}}
        @onContinue={{(noop)}}
        @noButtons={{false}}
      >
        <:default><span data-test-default>
            {{blockText}}
          </span></:default>
        <:buttons as |buttons|>
          <span data-test-buttons></span>
          <buttons.cancel /><buttons.continue /></:buttons>
        <:title><h1 data-test-title><b>{{title}}</b></h1> </:title>
      </Stargate>
    </template>);
```
Linting message
```
 Error in template: 'buttons' is not defined  no-undef

```

While the named block happens to be the same name as the yielded hash, I did try changing the names and the issue persisted. 

I have used yielded components elsewhere with no linting issue, assuming this is specific to named blocks

**Comment by NullVoxPopuli** [comment] 2023-08-10 16:11
what ember-source are you using? this is fixed in projects with sufficiently new ember-source, due to a fix landing in `@glimmer/syntax`'s parser

**Comment by cah-brian-gantzler** [comment] 2023-08-10 17:25
4.12.3.   Used to be I kept ember data and ember source in sync. Working through ED deprecations, so cant update to 5 for ED. Is it ok to update to 5 for source and keep ED at 4?

**Comment by cah-brian-gantzler** [comment] 2023-08-11 16:50
K, good to know, ember-code coverage looks like its bringing in 0.42 and and ember font awesome is bring in 0.27

**Comment by NullVoxPopuli** [comment] 2023-10-19 13:35
Should be resolved in v4. Thanks for reporting!
If this is still an issue, lemme know and we can reopen.

**Closed by NullVoxPopuli** 2023-10-19 13:35 UTC

**Comment by NullVoxPopuli** [comment] 2023-11-08 14:10
Can you try the main branch of eslint-plugin-ember?

**Comment by c0rydoras** [comment] 2023-11-08 14:20
sadly that did not fix it: https://github.com/c0rydoras/gjs-linting-no-undef-reproduction/actions/runs/6799482927/job/18485892842

**Comment by NullVoxPopuli** [comment] 2023-11-08 16:53
Interesting. Thanks for the reproduction! Can you open an issue on eslint plugin ember? Thanks!

**Comment by c0rydoras** [comment] 2023-11-08 18:23
done: https://github.com/ember-cli/eslint-plugin-ember/issues/1991
